package com.nyelam.android.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nyelam.android.data.dao.NYCountryCode;
import com.nyelam.android.data.dao.NYCategory;

import com.nyelam.android.data.dao.NYCountryCodeDao;
import com.nyelam.android.data.dao.NYCategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nYCountryCodeDaoConfig;
    private final DaoConfig nYCategoryDaoConfig;

    private final NYCountryCodeDao nYCountryCodeDao;
    private final NYCategoryDao nYCategoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nYCountryCodeDaoConfig = daoConfigMap.get(NYCountryCodeDao.class).clone();
        nYCountryCodeDaoConfig.initIdentityScope(type);

        nYCategoryDaoConfig = daoConfigMap.get(NYCategoryDao.class).clone();
        nYCategoryDaoConfig.initIdentityScope(type);

        nYCountryCodeDao = new NYCountryCodeDao(nYCountryCodeDaoConfig, this);
        nYCategoryDao = new NYCategoryDao(nYCategoryDaoConfig, this);

        registerDao(NYCountryCode.class, nYCountryCodeDao);
        registerDao(NYCategory.class, nYCategoryDao);
    }
    
    public void clear() {
        nYCountryCodeDaoConfig.clearIdentityScope();
        nYCategoryDaoConfig.clearIdentityScope();
    }

    public NYCountryCodeDao getNYCountryCodeDao() {
        return nYCountryCodeDao;
    }

    public NYCategoryDao getNYCategoryDao() {
        return nYCategoryDao;
    }

}
