package com.nyelam.android.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nyelam.android.data.dao.NYCountryCode;

import com.nyelam.android.data.dao.NYCountryCodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nYCountryCodeDaoConfig;

    private final NYCountryCodeDao nYCountryCodeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nYCountryCodeDaoConfig = daoConfigMap.get(NYCountryCodeDao.class).clone();
        nYCountryCodeDaoConfig.initIdentityScope(type);

        nYCountryCodeDao = new NYCountryCodeDao(nYCountryCodeDaoConfig, this);

        registerDao(NYCountryCode.class, nYCountryCodeDao);
    }
    
    public void clear() {
        nYCountryCodeDaoConfig.clearIdentityScope();
    }

    public NYCountryCodeDao getNYCountryCodeDao() {
        return nYCountryCodeDao;
    }

}
