package com.nyelam.android.data.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NYCATEGORY".
 */
@Entity
public class NYCategory {

    @Id
    private String id;
    private String name;
    private String iconUrl;
    private byte[] iconImage;

    @Generated
    public NYCategory() {
    }

    public NYCategory(String id) {
        this.id = id;
    }

    @Generated
    public NYCategory(String id, String name, String iconUrl, byte[] iconImage) {
        this.id = id;
        this.name = name;
        this.iconUrl = iconUrl;
        this.iconImage = iconImage;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public byte[] getIconImage() {
        return iconImage;
    }

    public void setIconImage(byte[] iconImage) {
        this.iconImage = iconImage;
    }

}
