package com.nyelam.android.data.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NYCOUNTRY_CODE".
 */
@Entity
public class NYCountryCode {

    @Id
    private String id;
    private String countryCode;
    private String countryName;
    private String countryNumber;
    private String countryImage;

    @Generated
    public NYCountryCode() {
    }

    public NYCountryCode(String id) {
        this.id = id;
    }

    @Generated
    public NYCountryCode(String id, String countryCode, String countryName, String countryNumber, String countryImage) {
        this.id = id;
        this.countryCode = countryCode;
        this.countryName = countryName;
        this.countryNumber = countryNumber;
        this.countryImage = countryImage;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    public String getCountryNumber() {
        return countryNumber;
    }

    public void setCountryNumber(String countryNumber) {
        this.countryNumber = countryNumber;
    }

    public String getCountryImage() {
        return countryImage;
    }

    public void setCountryImage(String countryImage) {
        this.countryImage = countryImage;
    }

}
